[package]
name = "dsc-resource-registry"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "registry"
path = "src/main.rs"

[package.metadata.i18n]
available-locales = ["en-us"]
default-locale = "en-us"
load-path = "locales"

[dependencies]
# external dependencies
clap = { workspace = true }
crossterm = { workspace = true }
registry = { workspace = true }
rust-i18n = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
utfx = { workspace = true }
# workspace crate dependencies
dsc-lib-registry = { workspace = true }
