[package]
name = "dsc_lib"
version = "3.0.0"
edition = "2021"

[dependencies]
base64 = "0.22"
chrono = { version = "0.4.26" }
derive_builder ="0.20"
indicatif = { version = "0.17" }
jsonschema = "0.17"
num-traits = "0.2"
regex = "1.7"
reqwest = { version = "0.12", features = ["blocking"] }
schemars = { version = "0.8.12", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_yaml = { version = "0.9.3" }
thiserror = "1.0"
security_context_lib = { path = "../security_context_lib" }
semver = "1.0"
tracing = "0.1.37"
tracing-indicatif = { version = "0.3.6" }
tree-sitter = "0.22"
tree-sitter-dscexpression = { path = "../tree-sitter-dscexpression" }

[dev-dependencies]
serde_yaml = "0.9.3"

[build-dependencies]
cc="*"
