[package]
name = "dsc_lib"
version = "3.0.0-alpha.5"
edition = "2021"

[dependencies]
base64 = "0.21"
derive_builder ="0.12"
jsonschema = "0.17"
regex = "1.7"
reqwest = { version = "0.11", features = ["blocking"] }
schemars = { version = "0.8.12", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "1.0"
chrono = "0.4.26"
tracing = "0.1.37"
tree-sitter = "~0.20.10"
tree-sitter-dscexpression = { path = "../tree-sitter-dscexpression" }

[dev-dependencies]
serde_yaml = "0.9.3"

[build-dependencies]
cc="*"
