[package]
name = "dsc_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_builder ="0.12"
jsonschema = "0.17"
regex = "1.7"
reqwest = { version = "0.11", features = ["blocking"] }
schemars = { version = "0.8.12", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
thiserror = "1.0"
