$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
# Try adding the variables, metadata, and parameters properties,
# then use IntelliSense to define a few entries.

resources:
  - type: example/resource
    name: My Example
    properties:
      foo: bar
  # Define a new resource instance
