[package]
name = "process"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.31"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
